### ISSUE TITLE
[feature-request] add a ci tests

### ISSUE THREAD

**Issue by duncdrum** [eXist-db/existdb-ansible-role#1]
the code is pretty black boxy and it is hard to tell if things are working as indended.

Setting up some basic ci tests, would be a good way to ensure code quality and catch errors early. 

I've found some examples of ansible ci-testing, and a [tutorial](https://www.ansible.com/blog/testing-ansible-roles-with-docker) which seems to offer a good starting point for setting this up here.

**Comment by chakl** [comment]
Duncdrum, thanks for the input, but there are currently no plans to implement that.
