### ISSUE TITLE
Add meta/main.yml in order to install role using Galaxy

### ISSUE THREAD

**Issue by jdwit** [eXist-db/existdb-ansible-role#2]
When trying to install this role using role using `ansible-galaxy install` I get ` [WARNING]: - existdb was NOT installed successfully: this role does not appear to have a meta/main.yml file.` This can be solved easily by adding a meta/main.yml file containing some metadata.

**Comment by chakl** [comment]
Jdwit, thanks for your contribution and sorry for leaving this hanging for so long! This will get merged into the upcoming 1.0 release, not on the old master branch.
