### ISSUE TITLE
[BUG] Installation fails on Ubuntu 22.04 (Jammy Jellfish) due to missing python-lxml

### ISSUE THREAD

**Issue by sermo-de-arboribus** [eXist-db/existdb-ansible-role#49]
On an Ubuntu 22.04 LTS the installation of eXist-db via this script fails with the error message 
`No package matching 'python-lxml' is available`

This package is not available from the apt-sources of this Ubuntu version. Therefore the defaults defined in the variable `exist_ubuntu_extra_packages` probably need to be adjusted.

**Expected behavior**
existdb-ansible-role should be able to install eXist-db on Ubuntu 22.04 LTS machines

**To Reproduce**
Just run this role against an Ubuntu 22.04 server with default settings, Java installed and being referenced through the `exist_java_home` variable.

**Comment by chakl** [comment]
Thanks for reporting.

Quick fix: for var `exist_ubuntu_extra_packages`, remove `python-lxml`. Does that work for you?

Correct fix: detect python 2-or-3 installation and adjust python package names based on that. Pending
